"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useState,useRef} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import type {getGroup} from "@/modules/groups/repository";
import {QrLink} from "@/components/player-tools/QrLink";
type Group=Awaited<ReturnType<typeof getGroup>>;
export function GroupWorkspace({id}:{id:string}) {
  const[group,setGroup]=useState<Group|null>(null),[message,setMessage]=useState("Loading your group…"),[busy,setBusy]=useState(false),[invite,setInvite]=useState(""),[guest,setGuest]=useState("");
  const token=useRef("");
  async function refresh(){const g=await toolRequest<Group>("/api/groups","PUT",{action:"READ",id,token:token.current||undefined});setGroup(g);return g;}
  useEffect(()=>{token.current=new URLSearchParams(location.hash.slice(1)).get("invite")??"";try{if(token.current)sessionStorage.setItem("ff-group-invite:"+id,JSON.stringify({token:token.current,expires:Date.now()+3600000}));else{const cached=JSON.parse(sessionStorage.getItem("ff-group-invite:"+id)||"null");if(cached?.expires>Date.now())token.current=cached.token;}}catch{/* The original link remains usable when browser session storage is blocked. */}if(token.current)setInvite(location.origin+"/groups/"+id+"#invite="+token.current);let active=true;const load=()=>{if(document.visibilityState!=="visible")return;void toolRequest<Group>("/api/groups","PUT",{action:"READ",id,token:token.current||undefined}).then(g=>{if(active){setGroup(g);setMessage("");}}).catch(e=>{if(active){setGroup(null);setMessage(e.message);}});};load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[id]);
  async function action(input:Record<string,unknown>){setBusy(true);try{const r=await toolRequest<{next?:string;token?:string}>("/api/groups","PUT",{...input,id});if(r.next){window.location.assign(r.next);return;}if(r.token){token.current=r.token;setInvite(location.origin+"/groups/"+id+"#invite="+r.token);}await refresh();setMessage("Group updated.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <ReadyControls><div className="feature-stack"><Link href="/groups">All groups</Link><p role="status">{message}</p>{!group?<p><Link href={`/sign-in?return_to=${encodeURIComponent("/groups/"+id)}`}>Sign in</Link> and <Link href="/community">finish Community setup</Link>, then reopen the invitation.</p>:<><header><span className="eyebrow">{group.visibility.toLowerCase()} group · {group.status.toLowerCase()}</span><h1>{group.courseName}</h1><p>{new Date(group.startsAt).toLocaleString()} · {group.pace.toLowerCase()} pace</p></header>{group.membership==="ACTIVE"?<div className="feature-actions"><button disabled={busy} className="button button-primary" onClick={()=>void action({action:"START"})}>Open my scorecard</button><Link href="/bag">Bag & caddie</Link>{!group.host?<button disabled={busy} onClick={()=>void action({action:"LEAVE"})}>Leave group and stop sharing scores</button>:null}</div>:<section className="feature-card"><p>{group.membership==="PENDING"?"Your request is waiting for the host.":"Your scores will be visible to approved group members when you join."}</p><button disabled={busy||group.membership==="PENDING"} onClick={()=>void action({action:"JOIN",token:token.current})}>Request to join</button></section>}
  {group.membership==="ACTIVE"?<section className="feature-card"><h2>Group scoreboard</h2><p>Updates every 15 seconds while visible. Each player edits only their own card; the host records guest scores.</p>{group.roster.map(m=><article className="feature-card" key={m.id}><h3>{m.name}{m.mine?" (you)":""}{m.guest?" (guest)":""}</h3><p>{m.status==="PENDING"?"Awaiting approval":`${m.scores.length} holes · ${m.scores.reduce((n,s)=>n+s.strokes+s.penalties,0)} strokes including penalties`}</p>{m.scores.length?<div className="score-strip">{m.scores.map(s=><span key={s.holeNumber}>H{s.holeNumber}: {s.strokes+s.penalties}</span>)}</div>:null}{group.host&&!m.mine?<div className="feature-actions">{m.status==="PENDING"?<button disabled={busy} onClick={()=>void action({action:"MEMBER",memberId:m.id,approve:true})}>Approve</button>:null}<button disabled={busy} onClick={()=>void action({action:"MEMBER",memberId:m.id,approve:false})}>Remove from group</button></div>:null}{group.host&&m.guest?<GuestScore member={m} holes={group.context.holeCount} busy={busy} save={i=>action({...i,action:"SCORE",memberId:m.id,version:m.version})}/>:null}</article>)}</section>:null}
  {group.host?<details className="feature-card"><summary>Host controls</summary><div className="feature-actions"><button disabled={busy} onClick={()=>void action({action:"STATUS",status:group.status==="OPEN"?"LOCKED":"OPEN"})}>{group.status==="OPEN"?"Lock new joins":"Reopen group"}</button><button disabled={busy} onClick={()=>void action({action:"STATUS",status:"CLOSED"})}>End group</button><button disabled={busy} onClick={()=>void action({action:"INVITE"})}>Create new invitation link</button></div><p>New links invalidate older invitation links. Ending the group does not finish or delete anyone’s personal scorecard.</p>{invite?<QrLink url={invite} label="Share group invitation"/>:null}<form className="feature-form" onSubmit={e=>{e.preventDefault();void action({action:"GUEST",guestId:crypto.randomUUID(),name:guest});}}><label>Guest’s chosen nickname<input required maxLength={40} value={guest} onChange={e=>setGuest(e.target.value)}/></label><small>Ask the guest before sharing their nickname and scores. Do not enter contact details.</small><button disabled={busy}>Add guest</button></form></details>:null}</>}</div></ReadyControls>;
}
function GuestScore({member,holes,busy,save}:{member:Group["roster"][number];holes:number;busy:boolean;save:(i:Record<string,unknown>)=>Promise<void>}){const[hole,setHole]=useState(1),[strokes,setStrokes]=useState(3),[penalties,setPenalties]=useState(0);return <details><summary>Record or correct guest score</summary><form className="feature-form" onSubmit={e=>{e.preventDefault();void save({holeNumber:hole,strokes,penalties});}}><label>Hole<input type="number" min={1} max={holes} value={hole} onChange={e=>setHole(Number(e.target.value))}/></label><label>Strokes<input type="number" min={1} max={99} value={strokes} onChange={e=>setStrokes(Number(e.target.value))}/></label><label>Penalties<input type="number" min={0} max={20} value={penalties} onChange={e=>setPenalties(Number(e.target.value))}/></label><button disabled={busy}>Save guest score</button><small>Edits retain an audit history. {member.name}’s scores are shared only with the group.</small></form></details>;}
