"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useState} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import type {PassportStamp} from "@/modules/passport/repository";
export function PassportWorkspace({courses,signedIn}:{signedIn:boolean;courses:{id:string;name:string;state:string;slug:string}[]}) {
  const[stamps,setStamps]=useState<PassportStamp[]>([]),[message,setMessage]=useState("Loading passport…"),[busy,setBusy]=useState(false),[courseId,setCourse]=useState(courses[0]?.id??""),[date,setDate]=useState(""),[state,setState]=useState("PLAYED"),[challenge,setChallenge]=useState(false);
  useEffect(()=>{void toolRequest<{stamps:PassportStamp[]}>("/api/passport").then(r=>{setStamps(r.stamps);setMessage("");}).catch(e=>setMessage(e.message));},[]);
  async function save(id=courseId,next=state){setBusy(true);try{await toolRequest("/api/passport","PUT",{courseId:id,state:next,visitedOn:date||null});setStamps((await toolRequest<{stamps:PassportStamp[]}>("/api/passport")).stamps);setMessage("Passport saved privately.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  const played=stamps.filter(s=>s.state==="PLAYED");
  return <ReadyControls><div className="feature-stack"><p role="status">{message}</p><section className="feature-card"><h2>{played.length} course {played.length===1?"listing":"listings"} played</h2><label className="check-label"><input type="checkbox" checked={challenge} onChange={e=>setChallenge(e.target.checked)}/>Show my six-state challenge</label>{challenge?<div className="passport-states">{["ME","NH","VT","MA","CT","RI"].map(s=><div key={s}><strong>{s}</strong><span>{played.filter(p=>p.region===s).length} played</span></div>)}</div>:null}<small>Private by default. Layout listings count individually; this is not a count of distinct properties.</small></section><form className="feature-card feature-form" onSubmit={e=>{e.preventDefault();void save();}}><h2>Add to your passport</h2><label>Course<select value={courseId} onChange={e=>setCourse(e.target.value)}>{courses.map(c=><option value={c.id} key={c.id}>{c.name} · {c.state}</option>)}</select></label><label>Entry<select value={state} onChange={e=>setState(e.target.value)}><option value="PLAYED">I have played here</option><option value="WISHLIST">Want to play</option></select></label><label>Played date (optional)<input type="date" value={date} max={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><button disabled={busy} className="button button-primary">Save passport entry</button></form><section className="feature-card"><h2>Your stamps & wishlist</h2>{stamps.length?stamps.map(s=><article className="feature-row" key={s.courseId}><div><Link href={`/courses/${s.slug}`}>{s.name}</Link><p>{s.source.replaceAll("_"," ").toLowerCase()} · {s.region}{s.date?` · ${s.date.slice(0,10)}`:""}</p></div>{s.source!=="APP_RECORDED"?<button disabled={busy} onClick={()=>void save(s.courseId,"REMOVE")}>Remove entry</button>:<small>From your saved round</small>}</article>):<p>No stamps yet. Complete a round or add a historical visit.</p>}</section><Link className="button button-secondary" href="/plan">Plan a New England weekend</Link>{!signedIn?<Link href="/sign-in?return_to=%2Fpassport">Sign in to your private passport</Link>:null}</div></ReadyControls>;
}
