"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useState} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import type {PracticeSample,PracticeProfile} from "@/modules/practice/practice-repository";
import {readFieldworkSession} from "@/modules/fieldwork/measurement";
import type {ThrowMeasurement} from "@/modules/fieldwork/types";
export function PracticeWorkspace({discs}:{discs:{id:string;name:string}[]}) {
  const [history,setHistory]=useState<Array<PracticeSample&{discName:string}>>([]);
  const [profiles,setProfiles]=useState<PracticeProfile[]>([]);
  const [local,setLocal]=useState<ThrowMeasurement[]>([]);
  const [selected,setSelected]=useState("");
  const [discId,setDisc]=useState(discs[0]?.id??"");
  const [calibrate,setCalibrate]=useState(false);
  const [message,setMessage]=useState("Loading your practice history…");
  const [busy,setBusy]=useState(false);
  async function refresh(){const result=await toolRequest<{samples:typeof history;profiles:PracticeProfile[]}>("/api/practice");setHistory(result.samples);setProfiles(result.profiles);}
  useEffect(()=>{let active=true;void toolRequest<{samples:typeof history;profiles:PracticeProfile[]}>("/api/practice").then(r=>{if(active){setHistory(r.samples);setProfiles(r.profiles);setMessage("");}}).catch(e=>{if(active)setMessage(e.message);});const localTimer=setTimeout(()=>{try{const samples=readFieldworkSession(localStorage.getItem("flightforge.fieldwork.session.v1")).measurements;setLocal(samples);setSelected(samples[0]?.id??"");}catch{setMessage("Device measurements could not be read. Your account history is still available.");}},0);return()=>{active=false;clearTimeout(localTimer);};},[]);
  async function save(){const sample=local.find(s=>s.id===selected);if(!sample)return;setBusy(true);try{await toolRequest("/api/practice","PUT",{id:sample.id,discId,throwType:sample.throwType??"BACKHAND",distanceFeet:sample.distanceFeet,uncertaintyMeters:sample.estimatedUncertaintyMeters,useForCaddie:calibrate,measuredAt:sample.measuredAt});await refresh();setMessage("Saved privately. Caddie calibration uses at least three eligible throws.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function change(sample:PracticeSample,remove=false){setBusy(true);try{await toolRequest("/api/practice",remove?"DELETE":"PUT",remove?{id:sample.id,version:sample.version}:{...sample,useForCaddie:!sample.useForCaddie});await refresh();setMessage(remove?"Measurement deleted.":"Caddie permission updated.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <ReadyControls><div className="feature-stack"><p role="status">{message}</p><section className="feature-card"><h2>Connect a Fieldwork throw</h2>{!discs.length?<p><Link href="/bag">Add your first disc</Link> before linking measurements.</p>:!local.length?<p><Link href="/fieldwork">Measure and save a throw</Link> on this device first.</p>:<form onSubmit={e=>{e.preventDefault();void save();}} className="feature-form"><label>Saved measurement<select value={selected} onChange={e=>setSelected(e.target.value)}>{local.map(s=><option key={s.id} value={s.id}>{Math.round(s.distanceFeet)} ft · ±{Math.round(s.estimatedUncertaintyMeters*3.28084)} ft · {new Date(s.measuredAt).toLocaleDateString()}</option>)}</select></label><label>Physical disc<select value={discId} onChange={e=>setDisc(e.target.value)}>{discs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={calibrate} onChange={e=>setCalibrate(e.target.checked)}/>This was a representative controlled throw; allow caddie calibration.</label><button className="button button-primary" disabled={busy}>Save to my practice history</button></form>}<small>Only distance and uncertainty are uploaded, not GPS coordinates. Calibration excludes putting, unspecified standstills, uncertainty over 10 m or over 15% of distance. It does not measure stability, release angle, speed or spin.</small></section>
  <section className="feature-card"><h2>What your caddie has learned</h2>{profiles.length?profiles.map(p=><p key={p.discId+p.throwType}>{discs.find(d=>d.id===p.discId)?.name} · {p.throwType.toLowerCase()}: typical {Math.round(p.distance)} ft from {p.count} throws; range {Math.round(p.spread)} ft, average GPS uncertainty ±{Math.round(p.uncertainty*3.28084)} ft.</p>):<p>No calibrated distances yet. Three approved, sufficiently clear measurements of the same disc and throw are required.</p>}</section>
  <section className="feature-card"><h2>Saved measurements</h2>{!history.length?<p>No account measurements yet.</p>:history.map(s=><article className="feature-row" key={s.id}><div><strong>{s.discName} · {Math.round(s.distanceFeet)} ft</strong><p>{s.throwType.toLowerCase()} · ±{Math.round(s.uncertaintyMeters*3.28084)} ft · {new Date(s.measuredAt).toLocaleDateString()}</p></div><button disabled={busy} onClick={()=>void change(s)}>{s.useForCaddie?"Stop using for caddie":"Allow caddie use"}</button><button disabled={busy} onClick={()=>void change(s,true)}>Delete measurement</button></article>)}</section><Link href="/bag#caddie-chat">Ask your caddie</Link></div></ReadyControls>;
}
