import { z } from "zod";
import { getD1Database } from "@/db/runtime";
import { actor,body,handle,ToolError,audit } from "@/modules/player-tools/server";
import { getCourseById } from "@/modules/courses/demo-courses";
import {conditionSchema,courseUpdates,listConditions,postCondition} from "@/modules/courses/conditions-repository";
export function GET(request:Request){return handle(async()=>{const u=await actor(request);const courseId=new URL(request.url).searchParams.get("courseId");return courseId?{notices:await listConditions(courseId,u.id),following:Boolean(await getD1Database().prepare("SELECT 1 FROM follows WHERE follower_user_id=? AND target_type='COURSE' AND target_id=?").bind(u.id,courseId).first())}:courseUpdates(u.id);});}
export function POST(request:Request){return handle(async()=>postCondition((await actor(request,true)).id,await body(request,conditionSchema)));}
export function PUT(request:Request){return handle(async()=>{const u=await actor(request);const i=await body(request,z.object({courseId:z.string().max(120),following:z.boolean()}));if(!getCourseById(i.courseId))throw new ToolError("Course not found.",404);const db=getD1Database();if(i.following)await db.prepare("INSERT OR IGNORE INTO follows(id,follower_user_id,target_type,target_id,created_at) VALUES(?,?,'COURSE',?,?)").bind(crypto.randomUUID(),u.id,i.courseId,new Date().toISOString()).run();else await db.prepare("DELETE FROM follows WHERE follower_user_id=? AND target_type='COURSE' AND target_id=?").bind(u.id,i.courseId).run();return {following:i.following};});}
export function DELETE(request:Request){return handle(async()=>{const u=await actor(request);const {id}=await body(request,z.object({id:z.uuid()}));const db=getD1Database();const own=await db.prepare("SELECT id FROM course_conditions WHERE id=? AND source_user_id=?").bind(id,u.id).first();if(!own&&!u.roles.includes("PLATFORM_ADMIN"))throw new ToolError("You cannot retract this report.",403);await db.batch([db.prepare("UPDATE course_conditions SET expires_at=? WHERE id=?").bind(new Date().toISOString(),id),audit(u.id,"course_condition",id,"RETRACT")]);return {retracted:true};});}
