"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useState,useRef} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import type {leagueDetail} from "@/modules/leagues/repository";
import {weeklyStarts} from "@/modules/leagues/calendar";
type Detail=Awaited<ReturnType<typeof leagueDetail>>;
export function LeaguesWorkspace({templates}:{templates:{id:string;title:string;startsAt:string;timeZone:string}[]}) {
  const[leagues,setLeagues]=useState<{id:string;name:string;description:string}[]>([]),[detail,setDetail]=useState<Detail|null>(null),[message,setMessage]=useState("Loading leagues…"),[busy,setBusy]=useState(false),[name,setName]=useState(""),[description,setDescription]=useState(""),[templateId,setTemplate]=useState(templates[0]?.id??""),[weeks,setWeeks]=useState(6);
  useEffect(()=>{void toolRequest<{leagues:typeof leagues}>("/api/leagues").then(r=>{setLeagues(r.leagues);setMessage("");}).catch(e=>setMessage(e.message));},[]);
  async function run(work:()=>Promise<void>){setBusy(true);try{await work();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function open(id:string){setDetail(await toolRequest<Detail>("/api/leagues?id="+id));}
  async function change(input:unknown){await toolRequest("/api/leagues","PUT",input);if(detail)await open(detail.id);setMessage("League updated.");}
  const requestId=useRef<string|null>(null);
  const template=templates.find(t=>t.id===templateId);
  let dates:string[]=[];let dateError="";try{if(template)dates=weeklyStarts(template.startsAt,template.timeZone,weeks);}catch(e){dateError=(e as Error).message;}
  return <ReadyControls><div className="feature-stack"><p role="status">{message}</p><p><Link href="/sign-in?return_to=%2Fleagues">Sign in for RSVPs</Link> · <Link href="/events">All events</Link></p><section className="feature-card"><h2>Find your weekly round</h2>{leagues.length?leagues.map(l=><article className="feature-row" key={l.id}><div><h3>{l.name}</h3><p>{l.description}</p></div><button disabled={busy} onClick={()=>void run(()=>open(l.id))}>View schedule</button></article>):<p>No league schedules have been published yet.</p>}</section>
  {detail?<section className="feature-stack"><h2>{detail.name}</h2><p>{detail.description}</p><button disabled={busy} onClick={()=>void run(async()=>{const r=await toolRequest<{calendar:string}>("/api/leagues","PUT",{action:"CALENDAR",id:detail.id});const url=URL.createObjectURL(new Blob([r.calendar],{type:"text/calendar"}));const a=document.createElement("a");a.href=url;a.download="league-schedule.ics";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage("Calendar downloaded with a one-hour reminder. Re-download after schedule changes.");})}>Add schedule to calendar</button><p>RSVP is an attendance plan, not payment, a tee-time booking or tournament registration. Calendar imports are snapshots, not live subscriptions.</p>{detail.events.map(e=><article className="feature-card" key={e.id}><h3><Link href={`/events/${e.slug}`}>{e.title}</Link></h3><p>{new Date(e.startsAt).toLocaleString("en-US",{timeZone:e.timeZone})} · {e.timeZone} · {e.status.toLowerCase()}</p><p>{e.going}/{e.capacity??"open"} going · {e.waiting} waitlisted · Your RSVP: {e.rsvp?.toLowerCase()??"not set"}{e.attended?" · attended":""}</p>{e.entryFeeCents>0?<p>Fees are handled through the organizer’s registration process. Your RSVP does not include payment.</p>:null}<div className="feature-actions"><button disabled={busy||e.status!=="PUBLISHED"} onClick={()=>void run(()=>change({action:"RSVP",eventId:e.id,going:true}))}>RSVP / join waitlist</button><button disabled={busy||!e.rsvp} onClick={()=>void run(()=>change({action:"RSVP",eventId:e.id,going:false}))}>Cancel RSVP</button></div>{detail.manager?<details><summary>Private attendance roster</summary>{detail.roster.filter(r=>r.eventId===e.id).map(r=><article className="feature-row" key={r.id}><span>{r.name} · {r.status.toLowerCase()}</span><button disabled={busy||r.status!=="GOING"} onClick={()=>void run(()=>change({action:"ATTENDANCE",id:r.id,attended:!r.attended}))}>{r.attended?"Mark absent":"Mark attended"}</button></article>)}</details>:null}</article>)}</section>:null}
  <details className="feature-card"><summary>Coordinator: create a recurring league</summary>{templates.length?<form className="feature-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await toolRequest<{id:string}>("/api/leagues","POST",{id:requestId.current??(requestId.current=crypto.randomUUID()),name,description,templateId,weeks});setLeagues((await toolRequest<{leagues:typeof leagues}>("/api/leagues")).leagues);await open(r.id);setMessage("League and weekly events published.");});}}><label>League name<input required minLength={3} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>About this league<textarea required minLength={10} maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>First published event<select value={templateId} onChange={e=>setTemplate(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>Total weekly rounds<input type="number" min={1} max={12} value={weeks} onChange={e=>setWeeks(Math.min(12,Math.max(1,Number(e.target.value))))}/></label>{template?<details open><summary>Schedule preview · {template.timeZone}</summary><ol>{dates.map(s=><li key={s}>{new Date(s).toLocaleString("en-US",{timeZone:template.timeZone})}</li>)}</ol></details>:null}<p>Publishing creates these additional public events using the first event’s course, rules, fees and registration link. Review dates and update individual events in Manage Events.</p><p role="alert">{dateError}</p><button className="button button-primary" disabled={busy||Boolean(dateError)}>Publish league and recurring events</button></form>:<p>Create a future public event in <Link href="/events/manage">Manage Events</Link> first. Course-specific coordinator approval is required.</p>}</details></div></ReadyControls>;
}
