"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useState,useEffect} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import type {CourseNotice} from "../conditions-repository";
export function CourseUpdates({courseId,initial,signedIn}:{courseId:string;initial:CourseNotice[];signedIn:boolean}) {
  const[notices,setNotices]=useState(initial),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const[status,setStatus]=useState("OPEN"),[note,setNote]=useState(""),[hours,setHours]=useState(6),[following,setFollowing]=useState<boolean|null>(null);
  useEffect(()=>{if(signedIn)void toolRequest<{following:boolean}>(`/api/course-updates?courseId=${encodeURIComponent(courseId)}`).then(r=>setFollowing(r.following)).catch(()=>{/* Mutations surface authorization and connectivity errors. */});},[courseId,signedIn]);
  async function act(method:string,input:unknown){setBusy(true);try{await toolRequest("/api/course-updates",method,input);const r=await toolRequest<{notices:CourseNotice[];following:boolean}>(`/api/course-updates?courseId=${encodeURIComponent(courseId)}`);setNotices(r.notices);setFollowing(r.following);setMessage("Updated. Reports expire automatically; check with the operator before traveling.");if(method==="POST")setNote("");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <ReadyControls><section className="feature-card"><h2>Can I play here today?</h2><p>Recent reports, not a guarantee of access. Player reports expire within 24 hours; operator updates within 72 hours.</p>{notices.length?notices.map(n=><article className="feature-row" key={n.id}><div><strong>{n.status.replaceAll("_"," ")} · {n.sourceType==="OPERATOR"?"Course operator":"Player report"}</strong><p>{n.note}</p><small>{new Date(n.observedAt).toLocaleString()} · expires {new Date(n.expiresAt).toLocaleString()}</small></div>{n.mine?<button disabled={busy} onClick={()=>void act("DELETE",{id:n.id})}>Retract report</button>:null}</article>):<p>No current reports. Confirm hours and conditions with the course.</p>}<p role="status">{message}</p>{signedIn?<><button disabled={busy} onClick={()=>void act("PUT",{courseId,following:following!==true})}>{following===true?"Unfollow course updates":"Follow in-app course updates"}</button><Link href="/updates">My course updates</Link><details><summary>Share a recent condition</summary><form className="feature-form" onSubmit={e=>{e.preventDefault();void act("POST",{id:crypto.randomUUID(),courseId,status,note,hours});}}><label>Condition<select value={status} onChange={e=>setStatus(e.target.value)}>{["OPEN","CLOSED","MUDDY","SNOW","ICE","MAINTENANCE","LAYOUT_CHANGE"].map(s=><option key={s}>{s}</option>)}</select></label><label>What did you observe?<textarea required minLength={5} maxLength={600} value={note} onChange={e=>setNote(e.target.value)}/></label><label>Useful for approximately<select value={hours} onChange={e=>setHours(Number(e.target.value))}><option value={3}>3 hours</option><option value={6}>6 hours</option><option value={12}>12 hours</option><option value={24}>24 hours</option></select></label><button className="button button-primary" disabled={busy}>Post condition report</button><small>Do not post personal information. Reports are labeled according to your actual course-management permissions.</small></form></details></>:<Link href={`/sign-in?return_to=${encodeURIComponent("/updates")}`}>Sign in to follow or report</Link>}</section></ReadyControls>;
}
