import type { Metadata } from "next";
import Link from "next/link";
import { Disc3, Sparkles, Camera, Ruler, History, Users, MessageCircle, Heart, Shield, CalendarDays, ChevronRight, Settings } from "lucide-react";
import { getCurrentUser } from "@/modules/auth/current-user";
import { can } from "@/modules/auth/permissions";
import { nextAuthDestination } from "@/modules/auth/continuation";
import { SignOutButton } from "@/components/auth/SignOutButton";
export const metadata:Metadata={title:"Player tools",robots:{index:false,follow:false}};
const tools=[{title:"My bag",copy:"Discs and flight characteristics",href:"/bag",icon:Disc3},{title:"Caddie",copy:"Plan a shot with your own discs",href:"/bag#caddie-chat",icon:Sparkles},{title:"Camera coach",copy:"Record, review, and practice",href:"/coach",icon:Camera},{title:"Fieldwork",copy:"Find space and estimate throw distance",href:"/fieldwork",icon:Ruler},{title:"Round history",copy:"Reopen scores and personal results",href:"/rounds",icon:History},{title:"Saved courses",copy:"Your next-round shortlist",href:"/favorites",icon:Heart},{title:"Community",copy:"Find players and course conversations",href:"/community",icon:Users},{title:"Messages",copy:"Your private conversations",href:"/messages",icon:MessageCircle}];
export default async function MorePage(){const user=await getCurrentUser();return <main className="tools-page page-shell"><header><span className="eyebrow">Your game, together</span><h1>More</h1><p>{user?user.displayName:"Player tools and account settings"}</p></header><nav className="tool-directory" aria-label="All player tools">{tools.map(({title,copy,href,icon:Icon})=><Link key={title} href={href}><Icon aria-hidden="true"/><span><strong>{title}</strong><small>{copy}</small></span><ChevronRight aria-hidden="true"/></Link>)}</nav><section className="account-tools"><h2>Account & privacy</h2>{user?<><Link className="button button-secondary" href={nextAuthDestination(user,"/profile")}><Settings aria-hidden="true"/>Profile & privacy</Link>{can(user,"manageEvents")?<Link href="/events/manage"><CalendarDays/>Manage events</Link>:null}{can(user,"viewAdmin")?<Link href="/admin"><Shield/>Administration</Link>:null}<SignOutButton variant="standalone"/></>:<><Link className="button button-primary" href="/sign-in?return_to=%2Fmore">Sign in</Link><Link className="button button-secondary" href="/sign-up?return_to=%2Fmore">Create free account</Link></>}</section></main>;}
