import type { Course } from "./types";

export const courses: Course[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    slug: "sabattus-disc-golf",
    name: "Sabattus Disc Golf",
    shortDescription:
      "A source-reviewed destination listing in central Maine. Course details remain intentionally concise until the operator verifies them.",
    city: "Sabattus",
    state: "ME",
    countryCode: "US",
    postalCode: "04280",
    addressLine1: "605 Bowdoinham Road",
    latitude: 44.1192,
    longitude: -70.1042,
    holeCount: 54,
    layoutCount: 3,
    difficulty: "INTERMEDIATE",
    terrain: ["Wooded", "Mixed", "Rolling"],
    amenities: ["Pro shop", "Restrooms", "Practice basket", "Disc rentals"],
    priceType: "PAID",
    priceFromCents: null,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "Sabattus Disc Golf",
    sourceUrl: "https://sabattusdiscgolf.com/pages/contact-sabattus-disc-golf",
    sourceType: "COURSE_OWNER",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "pine",
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    slug: "pineland-farms-disc-golf",
    name: "Pineland Farms Disc Golf",
    shortDescription:
      "A multi-course recreation property listing sourced from the operator's public recreation page.",
    city: "New Gloucester",
    state: "ME",
    countryCode: "US",
    postalCode: "04260",
    addressLine1: "15 Farm View Drive",
    latitude: 43.9048,
    longitude: -70.2577,
    holeCount: 54,
    layoutCount: 3,
    difficulty: "INTERMEDIATE",
    terrain: ["Mixed", "Rolling", "Open"],
    amenities: ["Food & drinks", "Disc rentals", "Pro shop", "Restrooms"],
    priceType: "PAID",
    priceFromCents: 800,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "Pineland Farms",
    sourceUrl: "https://pinelandfarms.org/recreation/summer/disc-golf/",
    sourceType: "COURSE_OWNER",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "meadow",
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    slug: "pleasant-hill-disc-golf",
    name: "Pleasant Hill Disc Golf",
    shortDescription:
      "An 18-hole southern Maine listing with broad fairways and water features, summarized from operator-published facts.",
    city: "Scarborough",
    state: "ME",
    countryCode: "US",
    postalCode: "04074",
    addressLine1: "38 Chamberlain Road",
    latitude: 43.5848,
    longitude: -70.3446,
    holeCount: 18,
    layoutCount: 1,
    difficulty: "RECREATIONAL",
    terrain: ["Open", "Mixed", "Flat"],
    amenities: ["Pro shop", "Restrooms", "Practice basket"],
    priceType: "PAID",
    priceFromCents: null,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "Pleasant Hill Disc Golf",
    sourceUrl: "https://philldiscgolf.com/",
    sourceType: "COURSE_OWNER",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "lake",
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    slug: "ackers-acres",
    name: "Acker’s Acres",
    shortDescription:
      "A two-course Bowdoinham property represented with factual directory fields only while ownership remains unverified.",
    city: "Bowdoinham",
    state: "ME",
    countryCode: "US",
    postalCode: "04008",
    addressLine1: "180 Dingley Road",
    latitude: 44.0176,
    longitude: -69.8992,
    holeCount: 36,
    layoutCount: 2,
    difficulty: "ADVANCED",
    terrain: ["Wooded", "Rolling"],
    amenities: ["Camping", "Practice basket"],
    priceType: "PAID",
    priceFromCents: null,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "PDGA Course Directory",
    sourceUrl: "https://www.pdga.com/course-directory/course/ackers-acres-wicked",
    sourceType: "PDGA_DIRECTORY",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "granite",
  },
  {
    id: "20000000-0000-4000-8000-000000000005",
    slug: "augusta-disc-golf",
    name: "Augusta Disc Golf",
    shortDescription:
      "A property-level Augusta listing created for operator review; individual layouts will be normalized after a successful claim.",
    city: "Augusta",
    state: "ME",
    countryCode: "US",
    postalCode: "04330",
    addressLine1: null,
    latitude: 44.3106,
    longitude: -69.7795,
    holeCount: 27,
    layoutCount: 2,
    difficulty: "INTERMEDIATE",
    terrain: ["Wooded", "Mixed", "Hilly"],
    amenities: ["Practice basket", "Restrooms"],
    priceType: "PAID",
    priceFromCents: null,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "PDGA Course Directory",
    sourceUrl:
      "https://www.pdga.com/course-directory/advanced/search?field_course_location_administrative_area=ME&field_course_location_country=US&location_title=Maine",
    sourceType: "PDGA_DIRECTORY",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "sunrise",
  },
  {
    id: "20000000-0000-4000-8000-000000000006",
    slug: "devils-grove-disc-golf",
    name: "Devil’s Grove Disc Golf",
    shortDescription:
      "A two-course Lewiston destination listing using operator-published location and amenity facts.",
    city: "Lewiston",
    state: "ME",
    countryCode: "US",
    postalCode: "04240",
    addressLine1: "455 Grove Street",
    latitude: 44.0815,
    longitude: -70.1291,
    holeCount: 36,
    layoutCount: 2,
    difficulty: "ADVANCED",
    terrain: ["Wooded", "Hilly"],
    amenities: ["Pro shop", "Restrooms", "Practice basket", "Dog-friendly"],
    priceType: "PAID",
    priceFromCents: 1000,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "Devil's Grove Disc Golf",
    sourceUrl: "https://devilsgrovediscgolf.com/",
    sourceType: "COURSE_OWNER",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "pine",
  },
  {
    id: "20000000-0000-4000-8000-000000000007",
    slug: "beaver-brook-disc-golf-course",
    name: "Beaver Brook Disc Golf Course",
    shortDescription:
      "A seasonal North Monmouth course listing sourced from public directory facts and queued for operator verification.",
    city: "North Monmouth",
    state: "ME",
    countryCode: "US",
    postalCode: "04265",
    addressLine1: "1 Wilson Pond Road",
    latitude: 44.291,
    longitude: -70.0731,
    holeCount: 18,
    layoutCount: 1,
    difficulty: "RECREATIONAL",
    terrain: ["Wooded", "Hilly"],
    amenities: ["Camping", "Pro shop"],
    priceType: "PAID",
    priceFromCents: null,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "PDGA Course Directory",
    sourceUrl: "https://www.pdga.com/course-directory/course/beaver-brook-disc-golf-course",
    sourceType: "PDGA_DIRECTORY",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "lake",
  },
  {
    id: "20000000-0000-4000-8000-000000000008",
    slug: "emcc-disc-golf-course",
    name: "EMCC Disc Golf Course",
    shortDescription:
      "A compact campus course listing sourced from Eastern Maine Community College's public course page.",
    city: "Bangor",
    state: "ME",
    countryCode: "US",
    postalCode: "04401",
    addressLine1: null,
    latitude: 44.8298,
    longitude: -68.7442,
    holeCount: 9,
    layoutCount: 1,
    difficulty: "BEGINNER",
    terrain: ["Mixed", "Flat"],
    amenities: ["Disc rentals", "Accessible route nearby"],
    priceType: "FREE",
    priceFromCents: 0,
    claimStatus: "UNCLAIMED",
    dataVerificationStatus: "REVIEWED_SOURCE_ONLY",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "Eastern Maine Community College",
    sourceUrl: "https://www.emcc.edu/student-life/life-at-emcc/disc-golf/",
    sourceType: "PUBLIC_AGENCY",
    verifiedBadge: false,
    fictionalDemo: false,
    currentCondition: null,
    conditionSource: null,
    nextAvailableAt: null,
    heroTone: "meadow",
  },
  {
    id: "20000000-0000-4000-8000-000000000009",
    slug: "forge-ridge-disc-golf-club-demo",
    name: "Forge Ridge Disc Golf Club",
    shortDescription:
      "A clearly fictional, operator-verified course used to demonstrate live availability and condition states without misrepresenting a real venue.",
    city: "Bridgton",
    state: "ME",
    countryCode: "US",
    postalCode: "04009",
    addressLine1: "Demonstration listing — no physical venue",
    latitude: 44.0434,
    longitude: -70.7121,
    holeCount: 18,
    layoutCount: 3,
    difficulty: "INTERMEDIATE",
    terrain: ["Wooded", "Mixed", "Hilly"],
    amenities: [
      "Pro shop",
      "Restrooms",
      "Food & drinks",
      "Disc rentals",
      "Practice basket",
      "Lessons",
      "GPS maps",
    ],
    priceType: "PAID",
    priceFromCents: 900,
    claimStatus: "VERIFIED",
    dataVerificationStatus: "FICTIONAL_DEMO",
    lastReviewedAt: "2026-08-03T12:00:00.000Z",
    sourceName: "FlightForge demonstration data",
    sourceUrl: "https://flightforge.example/demo-data",
    sourceType: "COURSE_OWNER",
    verifiedBadge: true,
    fictionalDemo: true,
    currentCondition: "Open · fairways dry",
    conditionSource: "DEMO",
    nextAvailableAt: "Today · 3:40 PM",
    heroTone: "sunrise",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  return courses.find((course) => course.slug === slug);
}

export function getCourseById(id: string): Course | undefined {
  return courses.find((course) => course.id === id);
}

export function formatCoursePrice(course: Course): string {
  if (course.priceType === "FREE") return "Free";
  if (course.priceFromCents == null) return "See course pricing";
  return `From $${(course.priceFromCents / 100).toFixed(0)}`;
}
