"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useState} from "react";
import {itinerary,clockLabel,planSchema,type Plan} from "@/modules/itineraries/planning";
import {toolRequest} from "@/modules/player-tools/client";
export function Planner({courses}:{courses:{id:string;name:string;state:string;difficulty:string;holes:number;slug:string}[]}) {
  const[plan,setPlan]=useState<Plan>({date:new Date().toISOString().slice(0,10),startMinutes:540,daylightCutoffMinutes:1080,bufferMinutes:45,stops:[]}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[region,setRegion]=useState("ALL"),[difficulty,setDifficulty]=useState("ALL");
  const available=courses.filter(c=>(region==="ALL"||c.state===region)&&(difficulty==="ALL"||c.difficulty===difficulty));
  async function persist(method:string){setBusy(true);try{const r=await toolRequest<{plan:Plan|null}>("/api/itinerary",method,method==="PUT"?plan:undefined);if(method==="GET"){if(r.plan)setPlan(r.plan);setMessage(r.plan?"Saved plan loaded.":"No saved plan yet.");}else setMessage(method==="PUT"?"Plan saved privately.":"Saved plan deleted.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  const validPlan=planSchema.safeParse(plan).success;
  const minutes=(s:string)=>Number(s.split(":")[0])*60+Number(s.split(":")[1]);
  return <ReadyControls><div className="feature-stack"><section className="feature-card feature-form"><h2>Your time budget</h2><label>First day<input type="date" value={plan.date} onChange={e=>setPlan({...plan,date:e.target.value})}/></label><label>Daily start<input type="time" value={clockLabel(plan.startMinutes).padStart(5,"0")} onChange={e=>setPlan({...plan,startMinutes:minutes(e.target.value)})}/></label><label>Daylight cutoff — check local sunset<input type="time" value={clockLabel(plan.daylightCutoffMinutes).padStart(5,"0")} onChange={e=>setPlan({...plan,daylightCutoffMinutes:minutes(e.target.value)})}/></label><label>Finish-before-dark buffer (minutes)<input type="number" min={0} max={120} value={plan.bufferMinutes} onChange={e=>setPlan({...plan,bufferMinutes:Number(e.target.value)})}/></label><p>The cutoff is your planning assumption, not a sunset forecast. Driving times, weather, opening hours and reservations are not checked automatically.</p></section>
  <section className="feature-card feature-form"><h2>Choose courses</h2><label>State<select value={region} onChange={e=>setRegion(e.target.value)}>{["ALL","ME","NH","VT","MA","CT","RI"].map(s=><option key={s}>{s}</option>)}</select></label><label>Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{["ALL","BEGINNER","RECREATIONAL","INTERMEDIATE","ADVANCED","UNRATED"].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={plan.stops.length>=8||!available.length} onClick={()=>setPlan({...plan,stops:[...plan.stops,{courseId:available[0].id,day:0,roundMinutes:120,travelMinutes:30,breakMinutes:20}]})}>Add course stop</button><small>Unrated means unknown, not beginner-friendly. Maximum eight stops.</small></section>
  {plan.stops.map((s,index)=><section className="feature-card feature-form" key={index}><h2>Stop {index+1}</h2><label>Course<select value={s.courseId} onChange={e=>setPlan({...plan,stops:plan.stops.map((v,j)=>j===index?{...v,courseId:e.target.value}:v)})}>{courses.filter(c=>available.some(a=>a.id===c.id)||c.id===s.courseId).map(c=><option key={c.id} value={c.id}>{c.name} · {c.state}</option>)}</select></label>{(["day","travelMinutes","roundMinutes","breakMinutes"] as const).map(key=><label key={key}>{({day:"Day (0 = first day, 1 = second day)",travelMinutes:"Travel before round (minutes)",roundMinutes:"Round allowance (minutes)",breakMinutes:"Break afterward (minutes)"})[key]}<input type="number" min={key==="roundMinutes"?15:0} max={key==="day"?1:key==="travelMinutes"?720:key==="roundMinutes"?360:180} value={s[key]} onChange={e=>setPlan({...plan,stops:plan.stops.map((v,j)=>j===index?{...v,[key]:Number(e.target.value)}:v)})}/></label>)}<button onClick={()=>setPlan({...plan,stops:plan.stops.filter((_,j)=>j!==index)})}>Remove stop</button></section>)}
  <section className="feature-card"><h2>Your proposed itinerary</h2>{!plan.stops.length?<p>Add a course to build your timeline.</p>:!validPlan?<p role="status">Enter a valid date and time budget to see your itinerary.</p>:itinerary(plan).map((s,i)=>{const c=courses.find(c=>c.id===s.courseId);return <article className="feature-row" key={i}><div><strong>{s.date} · {clockLabel(s.arrival)}–{clockLabel(s.finish)}</strong><p><Link href={`/courses/${c?.slug}`}>{c?.name}</Link></p>{s.overrun>0?<p role="status">Over your daylight budget by {s.overrun} minutes. Shorten or move this stop.</p>:<small>Within your entered time budget; confirm course access.</small>}</div></article>;})}</section><p role="status">{message}</p><div className="feature-actions"><button disabled={busy||!validPlan} onClick={()=>void persist("PUT")}>Save private plan</button><button disabled={busy} onClick={()=>void persist("GET")}>Load saved plan</button><button disabled={busy} onClick={()=>void persist("DELETE")}>Delete saved plan</button></div></div></ReadyControls>;
}
