import {beforeEach,afterEach,describe,expect,it,vi} from "vitest";

const mocks=vi.hoisted(()=>({client:vi.fn(),exchange:vi.fn(),getUser:vi.fn(),getClaims:vi.fn(),oauth:vi.fn(),signOut:vi.fn(),resolve:vi.fn(),createIntent:vi.fn(),abandonIntent:vi.fn(),limit:vi.fn(),ready:vi.fn(),recoveryIntent:vi.fn(),verifyOtp:vi.fn()}));
vi.mock("@/lib/supabase/server",()=>({createSupabaseServerClient:mocks.client}));
vi.mock("next/headers",()=>({cookies:async()=>({get:()=>undefined})}));
vi.mock("@/modules/auth/account-repository",()=>({ACCOUNT_SESSION_COOKIE:"flightforge_session",PASSWORD_RECOVERY_INTENT_COOKIE:"recovery-intent",RegistrationConsentRequiredError:class extends Error{},resolveSupabaseAccount:mocks.resolve,createHostedSignupIntent:mocks.createIntent,abandonHostedSignupIntent:mocks.abandonIntent,revokeAccountSession:vi.fn(),createPasswordRecoveryIntent:mocks.recoveryIntent}));
vi.mock("@/lib/security/request-security",async()=>{const actual=await import("@/lib/security/request-origin");return {...actual,checkRateLimit:mocks.limit};});
vi.mock("@/modules/auth/registration-readiness",()=>({isRegistrationReady:mocks.ready}));

import {RegistrationConsentRequiredError} from "./account-repository";
import {POST as start} from "@/app/api/auth/google/route";
import {GET as callback} from "@/app/auth/google/callback/route";
import {POST as complete} from "@/app/api/auth/google/complete/route";
import {GET as legacyCallback} from "@/app/auth/callback/route";
import {googleIdentityFromUser} from "./google-identity";
import {isGoogleSignInEnabled,isSupabaseAuthorizeUrl} from "./google-config";

const origin="https://flightforge.example";
const identity={id:"4fbbfcec-ad75-4110-987d-5a794b278256",email:"player@example.test",email_confirmed_at:"2026-09-28T12:00:00Z",identities:[{provider:"google"}],user_metadata:{full_name:"Google Player"}};
const account={id:"player-id",email:identity.email,onboardingComplete:true,roles:["PLAYER"]};
function post(path:string,body:unknown,requestOrigin=origin){return new Request(origin+path,{method:"POST",headers:{origin:requestOrigin,"content-type":"application/json"},body:JSON.stringify(body)});}
beforeEach(()=>{
 vi.resetAllMocks();vi.stubEnv("GOOGLE_SIGN_IN_ENABLED","true");vi.stubEnv("NEXT_PUBLIC_SUPABASE_URL","https://project.supabase.co");vi.stubEnv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY","public-test-key");vi.stubEnv("NEXT_PUBLIC_APP_URL",origin);
 mocks.client.mockResolvedValue({auth:{signInWithOAuth:mocks.oauth,exchangeCodeForSession:mocks.exchange,getUser:mocks.getUser,getClaims:mocks.getClaims,signOut:mocks.signOut,verifyOtp:mocks.verifyOtp}});
 mocks.exchange.mockResolvedValue({data:{redirectType:null},error:null});mocks.getUser.mockResolvedValue({data:{user:identity},error:null});mocks.signOut.mockResolvedValue({error:null});mocks.resolve.mockResolvedValue(account);mocks.limit.mockResolvedValue({allowed:true});mocks.ready.mockReturnValue(true);mocks.createIntent.mockResolvedValue("app-recorded-consent");mocks.abandonIntent.mockResolvedValue(undefined);mocks.recoveryIntent.mockResolvedValue("recovery-token");
 mocks.oauth.mockResolvedValue({data:{url:"https://project.supabase.co/auth/v1/authorize?provider=google"},error:null});
});
afterEach(()=>vi.unstubAllEnvs());

describe("Google sign-in boundaries",()=>{
 it("stays off until deliberately configured",async()=>{vi.stubEnv("GOOGLE_SIGN_IN_ENABLED","false");expect(isGoogleSignInEnabled()).toBe(false);expect((await start(post("/api/auth/google",{}))).status).toBe(503);expect(mocks.oauth).not.toHaveBeenCalled();});
 it("rejects cross-origin initiation",async()=>{expect((await start(post("/api/auth/google",{},"https://evil.example"))).status).toBe(403);});
 it("starts PKCE with the trusted callback and preserves bag context",async()=>{const next="/bag?round=abc&hole=7#caddie-chat";expect((await start(post("/api/auth/google",{returnTo:next}))).status).toBe(200);expect(mocks.oauth).toHaveBeenCalledWith({provider:"google",options:{redirectTo:origin+"/auth/google/callback?next="+encodeURIComponent(next),skipBrowserRedirect:true,scopes:"openid email profile"}});});
 it("rejects non-provider redirects",async()=>{mocks.oauth.mockResolvedValue({data:{url:"https://evil.example"},error:null});expect((await start(post("/api/auth/google",{}))).status).toBe(503);expect(isSupabaseAuthorizeUrl("https://project.supabase.co.evil.example/auth/v1/authorize?provider=google")).toBe(false);});
 it("keeps a cancelled login on the requested app destination",async()=>{const response=await callback(new Request(origin+"/auth/google/callback?error=access_denied&next=%2Fbag"));expect(response.headers.get("location")).toBe(origin+"/sign-in?error=google_cancelled&return_to=%2Fbag");expect(mocks.exchange).not.toHaveBeenCalled();});
 it("rejects missing codes, recovery parameters and expired codes",async()=>{for(const suffix of ["","?code=abc&type=recovery","?code=abc&token_hash=fake"]){const r=await callback(new Request(origin+"/auth/google/callback"+suffix));expect(r.headers.get("location")).toContain("google_failed");}expect(mocks.exchange).not.toHaveBeenCalled();mocks.exchange.mockResolvedValue({data:{redirectType:null},error:{message:"Expired or missing verifier"}});expect((await callback(new Request(origin+"/auth/google/callback?code=expired"))).headers.get("location")).toContain("google_failed");expect(mocks.resolve).not.toHaveBeenCalled();});
 it("ignores spoofed metadata and unverified identities",async()=>{expect(googleIdentityFromUser({...identity,email_confirmed_at:undefined})).toBeNull();expect(googleIdentityFromUser({...identity,identities:[{provider:"email"}],user_metadata:{provider:"google"}})).toBeNull();mocks.getUser.mockResolvedValue({data:{user:{...identity,email_confirmed_at:null}},error:null});await callback(new Request(origin+"/auth/google/callback?code=abc"));expect(mocks.resolve).not.toHaveBeenCalled();});
 it("returns an existing player to their same-origin destination and passes flow identity",async()=>{const response=await callback(new Request(origin+"/auth/google/callback?code=abc&sb_flow_id=flow123&next=%2Fbag%23caddie-chat"));expect(response.headers.get("location")).toBe(origin+"/bag#caddie-chat");expect(mocks.exchange).toHaveBeenCalledWith("abc",{flowId:"flow123"});expect(response.headers.get("cache-control")).toBe("private, no-store");});
 it("never follows an external return URL",async()=>{const response=await callback(new Request(origin+"/auth/google/callback?code=abc&next=https://evil.example"));expect(new URL(response.headers.get("location")!).origin).toBe(origin);});
 it("requires app consent for a new Google account",async()=>{mocks.resolve.mockRejectedValue(new RegistrationConsentRequiredError());const response=await callback(new Request(origin+"/auth/google/callback?code=abc&next=%2Fplay"));expect(response.headers.get("location")).toBe(origin+"/auth/complete?return_to=%2Fplay");expect(mocks.createIntent).not.toHaveBeenCalled();});
 it("preserves legacy-password linking and onboarding gates",async()=>{mocks.resolve.mockResolvedValue({...account,identityLinkRequired:true});expect((await callback(new Request(origin+"/auth/google/callback?code=abc&next=%2Fbag"))).headers.get("location")).toBe(origin+"/account/link?return_to=%2Fbag");mocks.resolve.mockResolvedValue({...account,onboardingComplete:false});expect((await callback(new Request(origin+"/auth/google/callback?code=abc&next=%2Fbag"))).headers.get("location")).toBe(origin+"/onboarding?return_to=%2Fbag");});
 it("fails closed for an unavailable or suspended account",async()=>{mocks.resolve.mockRejectedValue(new Error("Account unavailable"));expect((await callback(new Request(origin+"/auth/google/callback?code=abc"))).headers.get("location")).toContain("google_failed");expect(mocks.signOut).toHaveBeenCalledWith({scope:"local"});});
 it("records consent only after verified explicit acceptance",async()=>{const bad=await complete(post("/api/auth/google/complete",{displayName:"Player",acceptTerms:false}));expect(bad.status).toBe(422);expect(mocks.createIntent).not.toHaveBeenCalled();const good=await complete(post("/api/auth/google/complete",{displayName:"Chosen Name",acceptTerms:true,returnTo:"/bag"}));expect(good.status).toBe(200);expect(mocks.createIntent).toHaveBeenCalledWith(identity.email);expect(mocks.resolve).toHaveBeenCalledWith({...googleIdentityFromUser(identity),displayName:"Chosen Name",registrationNonce:"app-recorded-consent"});});
 it("does not let untrusted completion JSON choose identity or bypass registration pause",async()=>{mocks.ready.mockReturnValue(false);expect((await complete(post("/api/auth/google/complete",{acceptTerms:true}))).status).toBe(503);mocks.ready.mockReturnValue(true);mocks.getUser.mockResolvedValue({data:{user:null},error:null});expect((await complete(post("/api/auth/google/complete",{displayName:"Player",acceptTerms:true,email:"victim@example.test"}))).status).toBe(401);expect(mocks.createIntent).not.toHaveBeenCalled();});
 it("does not allow a Google code to create recovery authority through the older callback",async()=>{const response=await legacyCallback(new Request(origin+"/auth/callback?code=abc&type=recovery"));expect(response.headers.get("location")).toContain("invalid_confirmation");expect(mocks.recoveryIntent).not.toHaveBeenCalled();});
 it("rejects a forged browser recovery marker on a valid OAuth token",async()=>{mocks.exchange.mockResolvedValue({data:{redirectType:"recovery",session:{access_token:"oauth-token"},user:identity},error:null});mocks.getClaims.mockResolvedValue({data:{claims:recoveryClaims("oauth")},error:null});const response=await legacyCallback(new Request(origin+"/auth/callback?code=oauth-code&type=recovery"));expect(response.headers.get("location")).toContain("invalid_confirmation");expect(mocks.recoveryIntent).not.toHaveBeenCalled();});
 it("accepts freshly signed recovery claims even without a browser marker",async()=>{mocks.exchange.mockResolvedValue({data:{session:{access_token:"recovery-token"},user:identity},error:null});mocks.getClaims.mockResolvedValue({data:{claims:recoveryClaims()},error:null});const response=await legacyCallback(new Request(origin+"/auth/callback?code=real-recovery&type=recovery"));expect(response.headers.get("location")).toContain("/account/update-password");expect(mocks.getClaims).toHaveBeenCalledWith("recovery-token");expect(mocks.getUser).toHaveBeenCalledWith("recovery-token");expect(mocks.recoveryIntent).toHaveBeenCalledWith(identity.id);});
 it("rejects unverifiable recovery signatures",async()=>{mocks.exchange.mockResolvedValue({data:{session:{access_token:"forged-token"},user:identity},error:null});mocks.getClaims.mockResolvedValue({data:null,error:{message:"Bad signature"}});await legacyCallback(new Request(origin+"/auth/callback?code=forged&type=recovery"));expect(mocks.recoveryIntent).not.toHaveBeenCalled();});
 it("preserves server-verified token-hash recovery",async()=>{mocks.verifyOtp.mockResolvedValue({error:null});expect((await legacyCallback(new Request(origin+"/auth/callback?token_hash=valid&type=recovery"))).headers.get("location")).toContain("/account/update-password");expect(mocks.verifyOtp).toHaveBeenCalledWith({token_hash:"valid",type:"recovery"});expect(mocks.recoveryIntent).toHaveBeenCalledWith(identity.id);});
});

function recoveryClaims(method="recovery") { const now=Math.floor(Date.now()/1000);return {sub:identity.id,iss:"https://project.supabase.co/auth/v1",aud:"authenticated",role:"authenticated",session_id:"new-session",iat:now,exp:now+3600,amr:[{method,timestamp:now}]}; }
