"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {toolRequest} from "@/modules/player-tools/client";
import {QrLink} from "@/components/player-tools/QrLink";
type Overview={tags:{id:string;label:string;publicListing:number}[];cases:{id:string;label:string;status:string}[];board:{id:string;label:string}[]};
type Conversation={id:string;status:string;owner:boolean;messages:{id:string;body:string;mine:boolean;createdAt:string}[]};
export function RecoveryWorkspace({discs,courses,signedIn}:{signedIn:boolean;discs:{id:string;name:string}[];courses:{id:string;name:string;state:string}[]}) {
  const[data,setData]=useState<Overview>({tags:[],cases:[],board:[]}),[message,setMessage]=useState("Loading recovery tools…"),[busy,setBusy]=useState(false),[discId,setDisc]=useState(discs[0]?.id??""),[label,setLabel]=useState(""),[courseId,setCourse]=useState(""),[publicListing,setPublic]=useState(false),[url,setUrl]=useState(""),[target,setTarget]=useState<{id:string;label:string}|null>(null),[text,setText]=useState(""),[conversation,setConversation]=useState<Conversation|null>(null);
  const token=useRef("");
  async function load(){setData(await toolRequest<Overview>("/api/recovery"+(courseId?"?course="+encodeURIComponent(courseId):"")));}
  useEffect(()=>{token.current=new URLSearchParams(location.hash.slice(1)).get("tag")??"";try{if(token.current)sessionStorage.setItem("ff-recovery-link",JSON.stringify({token:token.current,expires:Date.now()+3600000}));else{const cached=JSON.parse(sessionStorage.getItem("ff-recovery-link")||"null");if(cached?.expires>Date.now())token.current=cached.token;}}catch{/* Reopen the original QR link if session storage is unavailable. */}void toolRequest<Overview>("/api/recovery").then(d=>{setData(d);setMessage("");}).catch(e=>setMessage(e.message));if(token.current)void toolRequest<{id:string;label:string}>("/api/recovery","PUT",{action:"LOOKUP",token:token.current}).then(setTarget).catch(e=>setMessage(e.message));},[]);
  async function run(work:()=>Promise<void>){setBusy(true);try{await work();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  async function open(id:string){setConversation(await toolRequest<Conversation>("/api/recovery?case="+id));setText("");}
  return <ReadyControls><div className="feature-stack"><p role="status">{message}</p><p><Link href="/community">Adult community setup & safety</Link>{!signedIn?<> · <Link href="/sign-in?return_to=%2Frecover">Sign in</Link></>:null}</p><section className="feature-card"><h2>Safe reunions</h2><p>Ask for a distinctive mark or other identifying detail privately before arranging a handoff. Use a public meeting place or course staff. Never post an address, phone number or private identifying mark on a course board.</p></section>
  {target?<form className="feature-card feature-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await toolRequest<{id:string}>("/api/recovery","PUT",{action:"CONTACT",id:crypto.randomUUID(),token:token.current||undefined,tagId:target.id,body:text});await open(r.id);setTarget(null);await load();setMessage("Private contact request sent.");});}}><h2>Found {target.label}?</h2><label>Private identifying details and a safe return suggestion<textarea minLength={10} maxLength={1000} required value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy}>Contact owner privately</button></form>:null}
  <details className="feature-card"><summary>Create or replace a disc contact tag</summary><form className="feature-form" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await toolRequest<{token:string}>("/api/recovery","POST",{discId,label,courseId:courseId||null,publicListing});setUrl(location.origin+"/recover#tag="+r.token);await load();setMessage("New tag created. Previous tags and conversations for this disc have been closed.");});}}><label>Owned disc<select value={discId} required onChange={e=>setDisc(e.target.value)}><option value="">Choose a disc</option>{discs.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Public-safe label, for example “blue midrange”<input required minLength={3} maxLength={100} value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Course (optional unless listing a loss)<select value={courseId} onChange={e=>setCourse(e.target.value)}><option value="">No course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name} · {c.state}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={publicListing} onChange={e=>setPublic(e.target.checked)}/>Publish this generic label on the course lost-disc board.</label><button disabled={busy}>Create tag and revoke old tag</button></form>{url?<QrLink url={url} label="Disc return contact link"/>:null}<small>Save or print this QR now. Its secret link cannot be retrieved later; generate a replacement if needed.</small></details>
  <section className="feature-card"><h2>Your active tags</h2>{data.tags.length?data.tags.map(t=><article className="feature-row" key={t.id}><span>{t.label} · {t.publicListing?"On course board":"QR only"}</span><button disabled={busy} onClick={()=>void run(async()=>{await toolRequest("/api/recovery","PUT",{action:"REVOKE",id:t.id});await load();setMessage("Tag revoked and its recovery conversations closed.");})}>Revoke tag</button></article>):<p>No active tags yet.</p>}</section>
  <section className="feature-card feature-form"><h2>Course lost-disc board</h2><label>Course<select value={courseId} onChange={e=>setCourse(e.target.value)}><option value="">Choose a course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name} · {c.state}</option>)}</select></label><button disabled={busy||!courseId} onClick={()=>void run(load)}>View course board</button>{data.board.length?data.board.map(t=><article className="feature-row" key={t.id}><span>{t.label}</span><button disabled={busy} onClick={()=>void run(async()=>{token.current="";setTarget(await toolRequest("/api/recovery","PUT",{action:"LOOKUP",tagId:t.id}));setText("");})}>I may have found this</button></article>):<p>No lost-disc listings loaded.</p>}</section>
  <section className="feature-card"><h2>Private recovery conversations</h2>{data.cases.length?data.cases.map(c=><button key={c.id} disabled={busy} onClick={()=>void run(()=>open(c.id))}>{c.label} · {c.status.toLowerCase()}</button>):<p>No contacts yet. Owners and finders check this inbox for replies; there are no email or push alerts yet.</p>}</section>
  {conversation?<section className="feature-card"><h2>Recovery conversation</h2><p>{conversation.status.toLowerCase()} · Only you and the other person can see these messages.</p>{conversation.messages.map(m=><article className="feature-message" key={m.id}><strong>{m.mine?"You":"Other participant"}</strong><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleString()}</small></article>)}<form className="feature-form" onSubmit={e=>{e.preventDefault();void run(async()=>{await toolRequest("/api/recovery","PUT",{action:"MESSAGE",id:conversation.id,messageId:crypto.randomUUID(),body:text});await open(conversation.id);setMessage("Message sent.");});}}><label>Private reply<textarea maxLength={1000} required value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||conversation.status!=="OPEN"}>Send private reply</button></form><div className="feature-actions"><button disabled={busy} onClick={()=>void run(()=>open(conversation.id))}>Refresh replies</button>{(["CLOSE","DELETE","BLOCK"] as const).map(action=><button key={action} disabled={busy} onClick={()=>void run(async()=>{await toolRequest("/api/recovery","PUT",{action,id:conversation.id});setConversation(null);await load();setMessage(action==="DELETE"?"Conversation and messages deleted.":"Conversation closed.");})}>{action==="CLOSE"?"Returned / close":action==="DELETE"?"Delete conversation":"Block participant"}</button>)}</div></section>:null}</div></ReadyControls>;
}
