"use client";
import {ReadyControls} from "@/components/player-tools/ReadyControls";
import Link from "next/link";
import {useEffect,useState,useRef} from "react";
import {toolRequest} from "@/modules/player-tools/client";
export function GroupsWorkspace({courses,signedIn}:{signedIn:boolean;courses:{id:string;name:string;state:string;holes:number}[]}) {
  const[groups,setGroups]=useState<Array<{id:string;courseName:string;startsAt:string;pace:string;players:number;capacity:number;beginnersWelcome:number;mine:number}>>([]),[message,setMessage]=useState("Loading groups…"),[busy,setBusy]=useState(false);
  const[courseId,setCourse]=useState(courses[0]?.id??""),[time,setTime]=useState(""),[visibility,setVisibility]=useState("PRIVATE"),[capacity,setCapacity]=useState(4),[pace,setPace]=useState("RELAXED"),[beginners,setBeginners]=useState(true);
  useEffect(()=>{void toolRequest<{groups:typeof groups}>("/api/groups").then(r=>{setGroups(r.groups);setMessage("");}).catch(e=>setMessage(e.message));},[]);
  const requestId=useRef<string|null>(null);
  async function create(){setBusy(true);try{const c=courses.find(c=>c.id===courseId)!;const r=await toolRequest<{id:string;token?:string}>("/api/groups","POST",{id:requestId.current??(requestId.current=crypto.randomUUID()),courseId,layoutId:null,holeCount:c.holes||18,startsAt:new Date(time).toISOString(),visibility,capacity,pace,beginnersWelcome:beginners});window.location.assign(`/groups/${r.id}${r.token?"#invite="+r.token:""}`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
  return <ReadyControls><div className="feature-stack"><p role="status">{message}</p><p><Link href="/community">Community setup & safety</Link>{!signedIn?<> · <Link href="/sign-in?return_to=%2Fgroups">Sign in</Link></>:null}</p><section className="feature-card"><h2>Your groups & open invitations</h2>{groups.length?groups.map(g=><article className="feature-row" key={g.id}><div><Link href={`/groups/${g.id}`}>{g.courseName}</Link><p>{new Date(g.startsAt).toLocaleString()} · {g.pace.toLowerCase()} · {g.players}/{g.capacity} players</p><small>{g.mine?"Your group":g.beginnersWelcome?"Beginners welcome":"Ask the host about experience level"}</small></div></article>):<p>No groups available yet. Create one below or open a friend’s invitation.</p>}</section><details className="feature-card"><summary>Create a playing group</summary><form className="feature-form" onSubmit={e=>{e.preventDefault();void create();}}><label>Course<select value={courseId} onChange={e=>setCourse(e.target.value)}>{courses.map(c=><option key={c.id} value={c.id}>{c.name} · {c.state}</option>)}</select></label><label>Meetup time (your device’s time zone)<input type="datetime-local" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Who can discover it?<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="PRIVATE">Invitation link only</option><option value="PUBLIC">Discoverable by other players</option></select></label><label>Group size, including you<input type="number" min={2} max={8} value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><label>Pace<select value={pace} onChange={e=>setPace(e.target.value)}>{["RELAXED","STEADY","QUICK"].map(p=><option key={p}>{p}</option>)}</select></label><label className="check-label"><input type="checkbox" checked={beginners} onChange={e=>setBeginners(e.target.checked)}/>Beginners welcome</label><p>This is a playing invitation, not a course reservation. Confirm access and tee-time requirements separately. Group members can see each other’s shared scores.</p><button disabled={busy} className="button button-primary">Create group</button></form></details></div></ReadyControls>;
}
